author = "Lukas Burk"
description = "Yet Another {blogdown} Blog"
keywords = "blog,rstats,R,personal"
info = "Doing things with R, mostly"
#avatarurl = "images/jemus42.jpg"
gravatar = "jemus42@quantenbrot.de"
footercontent = "Bad at blogging since 2009!"

# For package shortcode (configurability++;)
# pkg_format = "<i class='fas fa-box'></i> {%s}"
pkg_format = "{%s}"
pkg_icon_cran = "<i class='fab fa-r-project'></i>"
pkg_icon_git = "<i class='fab fa-git-alt'></i>"

dateformat = "January 2, 2006"

hideFooter = false
hideCredits = false
hideCopyright = false
since = 2015

# Git Commit in Footer, uncomment the line below to enable it.
commit = "https://github.com/rbind/blog.jemu.name/tree/"

rtl = false

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorscheme = "auto"

# Series see also post count
maxSeeAlsoItems = 5

# Custom CSS
custom_css = ["css/littlefoot.css"]

# Custom SCSS (needs to be placed in /assets/, _not_ /static/)
custom_scss = ["scss/jemsu.scss"]

# Custom JS
custom_js = [
    "js/littlefoot.js",
    "js/jemsu.js",
    "js/matomo.js",
    "https://commento.jemu.name/js/count.js"
    ]
    
commentoUrl = "https://commento.jemu.name"

# Icons
favicon_16 = "/favicon-16x16.png"
favicon_32 = "/favicon-32x32.png"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]
    # siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    # serverURL = "analytics.example.com"

[[social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/jemus42/"
[[social]]
    name = "Gitea"
    icon = "fab fa-git-alt"
    weight = 2
    url = "https://git.tadaa-data.de/lukas"
[[social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/jemus42/"
[[social]]
    name = "Keybase"
    icon = "fab fa-keybase"
    weight = 4
    url = "https://keybase.io/jemus42"
[[social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 10
    url = "https://blog.jemu.name/index.xml"
    rel = "alternate"
    type = "application/rss+xml"
