#################################
## Hugo settings               ##
#################################

baseURL = "https://blog.jemu.name/"
DefaultContentLanguage = "en"
relativeURLs = false
languageCode = "en-us"
title = "Blog Jemu"
#theme = "hugo-redlounge-jemsu"
theme = "beautifulhugo"
metaDataFormat = "yaml"
enableEmoji = true

ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
Paginate = 7
preserveTaxonomyNames = false

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  show = "shows"
  package = "packages"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

#################################
## Theme-specific settings     ##
#################################

#################
# beautifulhugo #
#################

[Params]
  homeTitle = "The Blog Jemu" # Set a different text for the header on the home page
  subtitle = "This still exists"
  mainSections = ["post","posts"]
  logo = "images/Jemus42.jpg" # Expecting square dimensions
  favicon = "icons/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  showRelatedPosts = true
  hideAuthor = true

[Params.piwik]
  id = "12"
  server = "analytics.tadaa-data.de/"

[Author]
  name = "jemus42"
  website = "https://jemu.name"
  email = "dontspamme@jemu.name"
  github = "jemus42"
#  gitlab = "username"
  twitter = "jemus42"
#  reddit = "username"
#  linkedin = "username"
#  xing = "Lukas_Burk2"
  stackoverflow = "users/409362/jemus42"
#  instagram = "jemus42"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
  spotify = "jemus42"
  git-selfhosted = "git.tadaa-data.de/lukas"
  bandcamp = "jemus42"
#  paypal = "jemus42"
  mastodon = "cybre.space/@jemus42"

[[menu.main]]
    name = "About"
    url = "about"
    identifier = "about"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "projects"
    identifier = "projects"
    weight = 2

[[menu.main]]
    name = "Posts"
    url = "post"
    identifier = "posts"
    weight = 3

# Submenu for post taxonomies
[[menu.main]]
    name = "categories"
    url = "categories"
    parent = "posts"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    parent = "posts"
    weight = 2

[[menu.main]]
    name = "Shows"
    url = "shows"
    parent = "posts"
    weight = 3

[[menu.main]]
    name = "R Packages"
    url = "packages"
    parent = "posts"
    weight = 4
# End submenu for taxonomies

[[menu.main]]
    name = "Source"
    url = "https://github.com/rbind/blog.jemu.name"
    weight = "4"
