baseURL = "https://blog.jemu.name/"
DefaultContentLanguage = "en"
relativeURLs = false
languageCode = "en-us"
title = "Blog Jemu"
#theme = "hugo-redlounge-jemsu"
theme = "beautifulhugo"
metaDataFormat = "yaml"
enableEmoji = true

ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
Paginate = 5
preserveTaxonomyNames = true

[permalinks]
    post = "/:year/:month/:slug/"
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.taxonomies]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.taxonomies]]
    name = "Tags"
    url = "/tags/"
    weight = 1
[[menu.taxonomies]]
    name = "Shows"
    url = "/shows/"
    weight = 2
[[menu.taxonomies]]
    name = "Packages"
    url = "/packages/"
    weight = 3

#    # options for highlight.js (version, additional languages, and theme)
#    highlightjsVersion = "9.15.10"
#    highlightjsCDN = "//cdn.bootcss.com"
#    highlightjsLang = ["r", "yaml"]
#    highlightjsTheme = "monokai-sublime"
#    disable_highlight_theme = false

#    MathJaxCDN = "//cdn.bootcss.com"
#    MathJaxVersion = "3.0.0" # "2.7.1"

#    piwikID = "12"
#    piwikURL = "https://analytics.tadaa-data.de/"

#[params.customCSS]
#    bigfoot = "css/bigfoot-number.min.css"

[taxonomies]
  category = "categories"
  tag = "tags"
  show = "shows"
  package = "packages"

# beautifulhugo
[Params]
  homeTitle = "The Blog Jemu" # Set a different text for the header on the home page
  subtitle = "This still exists"
  mainSections = ["post","posts"]
  logo = "images/Jemus42.jpg" # Expecting square dimensions
  favicon = "icons/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  showRelatedPosts = true
  hideAuthor = true

[Params.piwik]
  id = "12"
  server = "analytics.tadaa-data.de/"

[Author]
  name = "jemus42"
  website = "https://jemu.name"
  email = "dontspamme@jemu.name"
  github = "jemus42"
#  gitlab = "username"
#  bitbucket = "username"
  twitter = "jemus42"
#  reddit = "username"
#  linkedin = "username"
#  xing = "Lukas_Burk2"
  stackoverflow = "users/409362/jemus42"
#  instagram = "jemus42"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
  spotify = "jemus42"
  git-selfhosted = "git.tadaa-data.de/lukas"
  bandcamp = "jemus42"
#  paypal = "jemus42"
  mastodon = "cybre.space/@jemus42"

[[menu.main]]
    name = "Posts"
    url = "post"
    identifier = "posts"
    weight = 3

[[menu.main]]
    name = "categories"
    url = "categories"
    parent = "posts"
    weight = 1


[[menu.main]]
    name = "Tags"
    url = "tags"
    parent = "posts"
    weight = 2

[[menu.main]]
    name = "Shows"
    url = "shows"
    parent = "posts"
    weight = 3

[[menu.main]]
    name = "R Packages"
    url = "packages"
    parent = "posts"
    weight = 4
