baseURL = "https://blog.jemu.name/"
relativeURLs = true
languageCode = "en-us"
title = "Blog Jemu"
theme = "hugo-redlounge-jemsu"
#theme = "hugo-lithium-theme-jms"
disqusShortname = "blogjemuname"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
googleAnalytics = "UA-52990941-5"
Paginate = 10

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.social]]
    name = "twitter"
    pre = "<i class='fa fa-github fa-lg'></i>"
    url = "https://github.com/jemus42"
    weight = 1
[[menu.social]]
    name = "github"
    pre = "<i class='fa fa-twitter fa-lg'></i>"
    url = "https://twitter.com/jemus42"
    weight = 2
[[menu.social]]
    name = "telegram"
    pre = "<i class='fa fa-telegram fa-lg'></i>"
    url = "https://t.me/jemus42"
    weight = 3
[[menu.social]]
    name = "mail"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:jemus42@quantenbrot.de"
    weight = 6

[params]
    # A few options in case of redlounge theme
    sidebartitle = "Blog Jemu"
    sidebartagline = "Whereever Blogs Go"
    sidebarphoto = "/images/Jemus42.jpg"
    sidebarphoto_webp = "/images/Jemus42.webp"
    author = "jemus42"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    disable_highlight_theme = true

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    piwikID = "12"
    piwikURL = "https://analytics.tadaa-data.de/"

    bigfoot = true
    gallery = "fresco"

[params.customCSS]
    bigfoot = "css/bigfoot-number.min.css"

[params.logo]
    url = "Jemus42.jpg"
    width = 50
    height = 50
    alt = "jms"

[taxonomies]
  category = "categories"
  tag = "tags"
  show = "shows"
  package = "packages"
