baseURL = "https://blog.jemu.name/"
relativeURLs = false
languageCode = "en-us"
title = "Blog Jemu"
theme = "hugo-redlounge-jemsu"
#theme = "hugo-lithium-theme-jms"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
Paginate = 5
preserveTaxonomyNames = true

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.taxonomies]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.taxonomies]]
    name = "Tags"
    url = "/tags/"
    weight = 1
[[menu.taxonomies]]
    name = "Shows"
    url = "/shows/"
    weight = 2
[[menu.taxonomies]]
    name = "Packages"
    url = "/packages/"
    weight = 3

[[menu.social]]
    name = "mastodon"
    pre = "<i class='fab fa-mastodon fa-lg'></i>"
    url = "https://cybre.space/@jemus42"
    weight = 1
[[menu.social]]
    name = "github"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/jemus42"
    weight = 2
[[menu.social]]
    name = "mail"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:jemus42@quantenbrot.de"
    weight = 3

[params]
    # A few options in case of redlounge theme
    sidebartitle = "Blog Jemu"
    sidebartagline = "Whereever Blogs Go"
    sidebarphoto = "/images/Jemus42.jpg"
    sidebarphoto_webp = "/images/Jemus42.webp"
    author = "jemus42"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "monokai-sublime"
    disable_highlight_theme = false

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    piwikID = "12"
    piwikURL = "https://analytics.tadaa-data.de/"

    bigfoot = true
    gallery = "fresco"

[params.customCSS]
    bigfoot = "css/bigfoot-number.min.css"

[params.logo]
    url = "Jemus42.jpg"
    width = 50
    height = 50
    alt = "jms"

[taxonomies]
  category = "categories"
  tag = "tags"
  show = "shows"
  package = "packages"
